# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaydata',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
