# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydata',
            name='shortcode',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
