# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaydata', '0002_displaydata_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaydata',
            name='shortcode',
            field=models.CharField(default='cfdefaultvalue', max_length=15),
        ),
    ]
