# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaydata', '0002_auto_20170315_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
