# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161020_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
