# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_kirrurl_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='info',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
